
export const ESSENTIAL_100_WORDS = [
  { word: "abandon", meaning: "버리다, 포기하다", example: "The baby was abandoned by its parents." },
  { word: "ability", meaning: "능력, 재능", example: "He has the ability to do the work." },
  { word: "able", meaning: "할 수 있는", example: "Will you be able to come?" },
  { word: "about", meaning: "대하여", example: "Tell me about your trip." },
  { word: "above", meaning: "위에", example: "The sun is above the clouds." },
  { word: "abroad", meaning: "해외에", example: "She often travels abroad." },
  { word: "absolute", meaning: "절대적인", example: "I have absolute trust in him." },
  { word: "accept", meaning: "받아들이다", example: "Please accept my apology." },
  { word: "access", meaning: "접근", example: "I can't access the file." },
  { word: "accident", meaning: "사고", example: "It was a complete accident." },
  { word: "account", meaning: "계좌, 설명", example: "I need to open a bank account." },
  { word: "achieve", meaning: "달성하다", example: "You can achieve your goals." },
  { word: "across", meaning: "건너서", example: "The shop is across the street." },
  { word: "act", meaning: "행동하다", example: "Think before you act." },
  { word: "active", meaning: "활동적인", example: "He is very active for his age." },
  { word: "activity", meaning: "활동", example: "Outdoor activities are fun." },
  { word: "actor", meaning: "배우", example: "He is a famous movie actor." },
  { word: "add", meaning: "더하다", example: "Add some salt to the soup." },
  { word: "address", meaning: "주소", example: "What is your home address?" },
  { word: "admire", meaning: "존경하다", example: "I admire your courage." },
  { word: "admit", meaning: "인정하다", example: "He admitted his mistake." },
  { word: "adult", meaning: "성인", example: "Tickets for adults are $10." },
  { word: "advance", meaning: "전진, 진보", example: "Technology is advancing fast." },
  { word: "advantage", meaning: "장점", example: "The main advantage is the price." },
  { word: "adventure", meaning: "모험", example: "They love mountain adventures." },
  { word: "advice", meaning: "조언", example: "Let me give you some advice." },
  { word: "afford", meaning: "여유가 되다", example: "I can't afford a new car." },
  { word: "afraid", meaning: "두려워하는", example: "Don't be afraid of dogs." },
  { word: "after", meaning: "후에", example: "I'll call you after dinner." },
  { word: "afternoon", meaning: "오후", example: "See you this afternoon." },
  { word: "again", meaning: "다시", example: "Try it again." },
  { word: "against", meaning: "대항하여", example: "The fight against crime." },
  { word: "age", meaning: "나이", example: "What is your age?" },
  { word: "agency", meaning: "대리점, 기관", example: "He works for a travel agency." },
  { word: "agree", meaning: "동의하다", example: "I agree with you." },
  { word: "ahead", meaning: "앞에", example: "Go straight ahead." },
  { word: "air", meaning: "공기", example: "Fresh air is good for you." },
  { word: "airport", meaning: "공항", example: "I'm going to the airport." },
  { word: "alive", meaning: "살아있는", example: "Is the fish still alive?" },
  { word: "all", meaning: "모든", example: "All students are here." },
  { word: "allow", meaning: "허용하다", example: "Please allow me to go." },
  { word: "almost", meaning: "거의", example: "It's almost midnight." },
  { word: "alone", meaning: "혼자", example: "I prefer to be alone." },
  { word: "along", meaning: "따라서", example: "Walk along the river." },
  { word: "already", meaning: "이미", example: "I've already eaten." },
  { word: "also", meaning: "또한", example: "She is also a teacher." },
  { word: "always", meaning: "항상", example: "I always wake up at six." },
  { word: "amazing", meaning: "놀라운", example: "The view is amazing." },
  { word: "ambition", meaning: "야망", example: "His ambition is to be CEO." },
  { word: "among", meaning: "사이에", example: "He was among the crowd." },
  { word: "amount", meaning: "양", example: "A large amount of money." },
  { word: "ancient", meaning: "고대의", example: "They visited ancient ruins." },
  { word: "angry", meaning: "화난", example: "Don't be angry with me." },
  { word: "animal", meaning: "동물", example: "Do you like animals?" },
  { word: "announce", meaning: "발표하다", example: "They announced the winner." },
  { word: "another", meaning: "또 다른", example: "Have another cup of tea." },
  { word: "answer", meaning: "대답", example: "What is the answer?" },
  { word: "anxiety", meaning: "불안", example: "He suffers from anxiety." },
  { word: "any", meaning: "어떤", example: "Do you have any ideas?" },
  { word: "anyone", meaning: "누구든", example: "Anyone can join us." },
  { word: "anything", meaning: "무엇이든", example: "Is anything wrong?" },
  { word: "anyway", meaning: "어쨌든", example: "Anyway, let's start." },
  { word: "apart", meaning: "떨어져서", example: "The two houses are far apart." },
  { word: "apartment", meaning: "아파트", example: "I live in a small apartment." },
  { word: "apologize", meaning: "사과하다", example: "You should apologize to her." },
  { word: "apparent", meaning: "분명한", example: "It was apparent he was sad." },
  { word: "appear", meaning: "나타나다", example: "A cat appeared on the wall." },
  { word: "apple", meaning: "사과", example: "I ate a red apple." },
  { word: "apply", meaning: "지원하다, 적용하다", example: "I applied for the job." },
  { word: "appoint", meaning: "임명하다", example: "He was appointed manager." },
  { word: "appreciate", meaning: "감사하다", example: "I appreciate your help." },
  { word: "approach", meaning: "접근하다", example: "Winter is approaching." },
  { word: "appropriate", meaning: "적절한", example: "Is this dress appropriate?" },
  { word: "approve", meaning: "승인하다", example: "My boss approved the plan." },
  { word: "area", meaning: "지역", example: "This is a quiet area." },
  { word: "argue", meaning: "논쟁하다", example: "Stop arguing about it." },
  { word: "arm", meaning: "팔", example: "He broke his left arm." },
  { word: "army", meaning: "군대", example: "He joined the army." },
  { word: "around", meaning: "주변에", example: "I'll be around all day." },
  { word: "arrange", meaning: "정리하다, 준비하다", example: "I arranged the books." },
  { word: "arrest", meaning: "체포하다", example: "The police arrested him." },
  { word: "arrive", meaning: "도착하다", example: "The train arrived late." },
  { word: "art", meaning: "예술", example: "She loves modern art." },
  { word: "article", meaning: "기사, 물건", example: "I read an article about it." },
  { word: "artificial", meaning: "인공의", example: "Artificial intelligence is cool." },
  { word: "as", meaning: "~로서, ~때", example: "As a student, I study hard." },
  { word: "ashamed", meaning: "부끄러운", example: "I felt ashamed of myself." },
  { word: "aside", meaning: "옆으로", example: "Stand aside, please." },
  { word: "ask", meaning: "묻다, 요청하다", example: "Ask him for the key." },
  { word: "asleep", meaning: "잠든", example: "The baby is fast asleep." },
  { word: "aspect", meaning: "측면", example: "Consider every aspect." },
  { word: "assign", meaning: "할당하다", example: "Teacher assigned homework." },
  { word: "assist", meaning: "돕다", example: "Can I assist you?" },
  { word: "assume", meaning: "추정하다", example: "Don't assume anything." },
  { word: "assure", meaning: "보장하다", example: "I assure you it's safe." },
  { word: "at", meaning: "~에", example: "Meet me at the park." },
  { word: "atmosphere", meaning: "대기, 분위기", example: "The atmosphere was tense." },
  { word: "attach", meaning: "첨부하다", example: "Attach your photo here." },
  { word: "attack", meaning: "공격하다", example: "Don't attack the messenger." },
  { word: "attempt", meaning: "시도하다", example: "He attempted to escape." },
  { word: "attend", meaning: "참석하다", example: "I'll attend the wedding." }
];

export const SPANISH_100_WORDS = [
  { word: "hola", meaning: "안녕", example: "¡Hola! ¿Cómo estás?" },
  { word: "adiós", meaning: "안녕 (헤어질 때)", example: "Adiós, nos vemos mañana." },
  { word: "gracias", meaning: "감사합니다", example: "Muchas gracias por tu ayuda." },
  { word: "por favor", meaning: "부탁합니다", example: "Un café, por favor." },
  { word: "amigo", meaning: "친구", example: "Él es mi mejor amigo." },
  { word: "casa", meaning: "집", example: "Esta es mi casa." },
  { word: "tiempo", meaning: "시간, 날씨", example: "No tengo mucho tiempo." },
  { word: "trabajo", meaning: "일, 직장", example: "Tengo mucho trabajo." },
  { word: "escuela", meaning: "학교", example: "Voy a la escuela." },
  { word: "comer", meaning: "먹다", example: "Me gusta comer pizza." },
  { word: "beber", meaning: "마시다", example: "Quiero beber algo." },
  { word: "hablar", meaning: "말하다", example: "Hablo español." },
  { word: "leer", meaning: "읽다", example: "Él lee un libro." },
  { word: "escribir", meaning: "쓰다", example: "Tengo que escribir." },
  { word: "amor", meaning: "사랑", example: "Te amo con todo mi corazón." },
  { word: "bueno", meaning: "좋은", example: "¡Qué buen día!" },
  { word: "malo", meaning: "나쁜", example: "No es un mal tipo." },
  { word: "grande", meaning: "큰", example: "Tengo un coche grande." },
  { word: "pequeño", meaning: "작은", example: "Es un perro pequeño." },
  { word: "mañana", meaning: "내일, 아침", example: "Hasta mañana." },
  { word: "hoy", meaning: "오늘", example: "Hoy es lunes." },
  { word: "ayer", meaning: "어제", example: "Ayer fui al cine." },
  { word: "feliz", meaning: "행복한", example: "Estoy muy feliz." },
  { word: "triste", meaning: "슬픈", example: "Ella está triste." },
  { word: "caliente", meaning: "뜨거운", example: "El café está caliente." },
  { word: "frío", meaning: "추운, 차가운", example: "Hace mucho frío hoy." },
  { word: "nuevo", meaning: "새로운", example: "Este es mi zapato nuevo." },
  { word: "viejo", meaning: "오래된, 늙은", example: "Mi abuelo es viejo." },
  { word: "querer", meaning: "원하다", example: "Quiero un helado." },
  { word: "poder", meaning: "할 수 있다", example: "No puedo ir contigo." },
  { word: "saber", meaning: "알다", example: "Yo no lo sé." },
  { word: "ver", meaning: "보다", example: "Quiero ver la televisión." },
  { word: "venir", meaning: "오다", example: "Ven aquí ahora." },
  { word: "ir", meaning: "가다", example: "Voy a la playa." },
  { word: "dar", meaning: "주다", example: "Dame el libro." },
  { word: "tomar", meaning: "마시다", example: "Voy a tomar un té." },
  { word: "llamar", meaning: "부르다", example: "Llamame más tarde." },
  { word: "buscar", meaning: "찾다", example: "Busco mis llaves." },
  { word: "comprar", meaning: "사다", example: "Quiero comprar pan." },
  { word: "vender", meaning: "팔다", example: "Él vende frutas." },
  { word: "familia", meaning: "가족", example: "Mi familia es grande." },
  { word: "padre", meaning: "아버지", example: "Mi padre es médico." },
  { word: "madre", meaning: "어머니", example: "Mi madre es profesora." },
  { word: "hijo", meaning: "아들", example: "Tengo un hijo." },
  { word: "hija", meaning: "딸", example: "Tengo una hija." },
  { word: "hermano", meaning: "형제, 남자형제", example: "Él es mi hermano." },
  { word: "hermana", meaning: "자매, 여자형제", example: "Ella es mi hermana." },
  { word: "agua", meaning: "물", example: "Quiero un vaso de agua." },
  { word: "pan", meaning: "빵", example: "El pan está fresco." },
  { word: "leche", meaning: "우유", example: "Me gusta la leche." },
  { word: "fruta", meaning: "과일", example: "Como mucha fruta." },
  { word: "carne", meaning: "고기", example: "No como carne." },
  { word: "verdura", meaning: "채소", example: "Me gustan las verduras." },
  { word: "ropa", meaning: "옷", example: "Tengo mucha ropa." },
  { word: "zapato", meaning: "신발", example: "Mi zapato es negro." },
  { word: "libro", meaning: "책", example: "Leo un libro." },
  { word: "ciudad", meaning: "도시", example: "Vivo en una ciudad grande." },
  { word: "calle", meaning: "거리", example: "La calle está vacía." },
  { word: "perro", meaning: "개", example: "Tengo un perro." },
  { word: "gato", meaning: "고양이", example: "Mi gato es blanco." },
  { word: "sol", meaning: "태양", example: "El sol brilla." },
  { word: "luna", meaning: "달", example: "La luna es hermosa." },
  { word: "estrella", meaning: "별", example: "Hay many estrellas." },
  { word: "mar", meaning: "바다", example: "El mar es azul." },
  { word: "río", meaning: "강", example: "El río es largo." },
  { word: "montaña", meaning: "산", example: "La montaña es alta." },
  { word: "flor", meaning: "꽃", example: "La flor es roja." },
  { word: "árbol", meaning: "나무", example: "El árbol es verde." },
  { word: "cielo", meaning: "하늘", example: "El cielo está despejado." },
  { word: "tierra", meaning: "지구, 땅", example: "La tierra es redonda." },
  { word: "fuego", meaning: "불", example: "El fuego quema." },
  { word: "aire", meaning: "공기", example: "El aire es puro." },
  { word: "viento", meaning: "바람", example: "Hace mucho viento." },
  { word: "lluvia", meaning: "비", example: "Me gusta la lluvia." },
  { word: "nieve", meaning: "눈", example: "La nieve es blanca." },
  { word: "día", meaning: "낮, 일", example: "Buenos días." },
  { word: "noche", meaning: "밤", example: "Buenas noches." },
  { word: "semana", meaning: "주", example: "La semana tiene siete días." },
  { word: "mes", meaning: "월", example: "El mes de mayo." },
  { word: "año", meaning: "년", example: "Feliz año nuevo." },
  { word: "hora", meaning: "시간", example: "¿Qué hora es?" },
  { word: "minuto", meaning: "분", example: "Espera un minuto." },
  { word: "segundo", meaning: "초", example: "Un segundo, por favor." },
  { word: "número", meaning: "숫자", example: "Mi número de teléfono." },
  { word: "persona", meaning: "사람", example: "Es una buena persona." },
  { word: "hombre", meaning: "남자", example: "Es un hombre alto." },
  { word: "mujer", meaning: "여자", example: "Es una mujer inteligente." },
  { word: "niño", meaning: "아이 (남아)", example: "El niño juega." },
  { word: "niña", meaning: "아이 (여아)", example: "La niña canta." },
  { word: "amiga", meaning: "친구 (여성)", example: "Ella es mi amiga." },
  { word: "país", meaning: "나라", example: "España es un país." },
  { word: "idioma", meaning: "언어", example: "Hablo tres idiomas." },
  { word: "mundo", meaning: "세계", example: "El mundo es grande." },
  { word: "paz", meaning: "평화", example: "Queremos la paz." },
  { word: "vida", meaning: "삶", example: "La vida es bella." },
  { word: "muerte", meaning: "죽음", example: "La muerte es natural." },
  { word: "salud", meaning: "건강", example: "La salud es lo primero." },
  { word: "dinero", meaning: "돈", example: "No tengo dinero." },
  { word: "precio", meaning: "가격", example: "El precio es alto." },
  { word: "tienda", meaning: "가게", example: "Voy a la tienda." }
];

export const JAPANESE_100_WORDS = [
  { word: "こんにちは [Konnichiwa]", meaning: "안녕하세요", example: "皆さん、こんにちは。" },
  { word: "ありがとう [Arigatō]", meaning: "감사합니다", example: "手伝ってくれてありがとう。" },
  { word: "さようなら [Sayōnara]", meaning: "안녕히 가세요", example: "先生、さようなら。" },
  { word: "すみません [Sumimasen]", meaning: "죄송합니다/실례합니다", example: "すみません、道を聞いてもいいですか？" },
  { word: "はい [Hai]", meaning: "네", example: "はい、承知しました。" },
  { word: "いいえ [Iie]", meaning: "아니요", example: "いいえ、大丈夫です。" },
  { word: "私 [Watashi]", meaning: "나, 저", example: "私は学生です。" },
  { word: "これ [Kore]", meaning: "이것", example: "これはいくらですか？" },
  { word: "おいしい [Oishii]", meaning: "맛있다", example: "このケーキはおいしいです。" },
  { word: "友達 [Tomodachi]", meaning: "친구", example: "彼は私の親友です。" },
  { word: "学校 [Gakkō]", meaning: "학교", example: "学校へ行きます。" },
  { word: "先生 [Sensei]", meaning: "선생님", example: "先生に質問します。" },
  { word: "日本語 [Nihongo]", meaning: "일본어", example: "日本語를 공부하고 있습니다." },
  { word: "家族 [Kazoku]", meaning: "가족", example: "家族で旅行に行きます。" },
  { word: "時間 [Jikan]", meaning: "시간", example: "時間がありません。" },
  { word: "名前 [Namae]", meaning: "이름", example: "お名前は何ですか？" },
  { word: "好き [Suki]", meaning: "좋아하다", example: "日本料理が好きです。" },
  { word: "今日 [Kyō]", meaning: "오늘", example: "今日はいい天気です。" },
  { word: "明日 [Ashita]", meaning: "내일", example: "明日は休みです。" },
  { word: "昨日 [Kinō]", meaning: "어제", example: "昨日は雨でした。" },
  { word: "行く [Iku]", meaning: "가다", example: "デパートに行きます。" },
  { word: "来る [Kuru]", meaning: "오다", example: "友達が遊びに来ます。" },
  { word: "食べる [Taberu]", meaning: "먹다", example: "リンゴを食べます。" },
  { word: "飲む [Nomu]", meaning: "마시다", example: "お茶を飲みます。" },
  { word: "見る [Miru]", meaning: "보다", example: "映画を見ます。" },
  { word: "書く [Kaku]", meaning: "쓰다", example: "手紙を書きます。" },
  { word: "聞く [Kiku]", meaning: "듣다", example: "音楽を聞きます。" },
  { word: "話す [Hanasu]", meaning: "말하다", example: "日本語で話します。" },
  { word: "寝る [Neru]", meaning: "자다", example: "早く寝ます。" },
  { word: "起きる [Okiru]", meaning: "일어나다", example: "六時に起きます。" },
  { word: "本 [Hon]", meaning: "책", example: "本を読みます。" },
  { word: "水 [Mizu]", meaning: "물", example: "水を飲みます。" },
  { word: "お茶 [Ocha]", meaning: "차", example: "お茶をどうぞ。" },
  { word: "ご飯 [Gohan]", meaning: "밥", example: "ご飯を食べましょう。" },
  { word: "魚 [Sakana]", meaning: "생선", example: "魚が好きです。" },
  { word: "肉 [Niku]", meaning: "고기", example: "肉を食べます。" },
  { word: "野菜 [Yasai]", meaning: "야채", example: "野菜は体にいいです。" },
  { word: "果물 [Kudamono]", meaning: "과일", example: "果物を買います。" },
  { word: "飲み物 [Nomimono]", meaning: "음료", example: "冷たい飲み物がいいです。" },
  { word: "車 [Kuruma]", meaning: "자동차", example: "車で行きます。" },
  { word: "電車 [Densha]", meaning: "전철", example: "電車に乗ります。" },
  { word: "家 [Ie]", meaning: "집", example: "家に帰ります。" },
  { word: "部屋 [Heya]", meaning: "방", example: "私の部屋はきれいです。" },
  { word: "机 [Tsukue]", meaning: "책상", example: "机の上に本があります。" },
  { word: "椅子 [Isu]", meaning: "의자", example: "椅子に座ります。" },
  { word: "電話 [Denwa]", meaning: "전화", example: "電話를 겁니다." },
  { word: "時計 [Tokei]", meaning: "시계", example: "時計を見ます。" },
  { word: "お金 [Okane]", meaning: "돈", example: "お金がありません。" },
  { word: "店 [Mise]", meaning: "가게", example: "店へ買い物に行きます。" },
  { word: "買い物 [Kaimono]", meaning: "쇼핑", example: "買い物をします。" },
  { word: "旅行 [Ryokō]", meaning: "여행", example: "日本へ旅行に行きます。" },
  { word: "映画 [Eiga]", meaning: "영화", example: "映画を見に行きます。" },
  { word: "音楽 [Ongaku]", meaning: "음악", example: "音楽を聞くのが好きです。" },
  { word: "写真 [Shashin]", meaning: "사진", example: "写真を撮ります。" },
  { word: "海 [Umi]", meaning: "바다", example: "海で泳ぎます。" },
  { word: "山 [Yama]", meaning: "산", example: "山に登ります。" },
  { word: "空 [Sora]", meaning: "하늘", example: "空が青いです。" },
  { word: "雨 [Ame]", meaning: "비", example: "雨が降っています。" },
  { word: "雪 [Yuki]", meaning: "눈", example: "雪がきれいです。" },
  { word: "風 [Kaze]", meaning: "바람", example: "風が強いです。" },
  { word: "花 [Hana]", meaning: "꽃", example: "花が咲きました。" },
  { word: "木 [Ki]", meaning: "나무", example: "大きな木があります。" },
  { word: "犬 [Inu]", meaning: "개", example: "犬を飼っています。" },
  { word: "猫 [Neko]", meaning: "고양이", example: "猫が好きです。" },
  { word: "鳥 [Tori]", meaning: "새", example: "鳥が鳴いています。" },
  { word: "天気 [Tenki]", meaning: "날씨", example: "いい天気ですね。" },
  { word: "暑い [Atsui]", meaning: "덥다", example: "今日はとても暑いです。" },
  { word: "寒い [Samui]", meaning: "춥다", example: "外はとても寒いです。" },
  { word: "高い [Takai]", meaning: "높다, 비싸다", example: "この本は高いです。" },
  { word: "安い [Yasui]", meaning: "싸다", example: "このリンゴ는 저렴합니다." },
  { word: "大きい [Ōkii]", meaning: "크다", example: "大きな家です。" },
  { word: "小さい [Chiisai]", meaning: "작다", example: "小さな猫です。" },
  { word: "新しい [Atarashii]", meaning: "새롭다", example: "新しい靴を買いました。" },
  { word: "古い [Furui]", meaning: "오래되다", example: "古い建物です。" },
  { word: "忙しい [Isogashii]", meaning: "바쁘다", example: "今は忙しいです。" },
  { word: "楽しい [Tanoshii]", meaning: "즐겁다", example: "旅行は楽しいです。" },
  { word: "嬉しい [Ureshii]", meaning: "기쁘다", example: "会えて嬉しいです。" },
  { word: "悲しい [Kanashii]", meaning: "슬프다", example: "悲しい映画を見ました。" },
  { word: "面白い [Omoshiroi]", meaning: "재미있다", example: "この本は面白いです。" },
  { word: "難しい [Muzukashii]", meaning: "어렵다", example: "日本語は難しいです。" },
  { word: "易しい [Yasashii]", meaning: "쉽다", example: "この問題は易しいです。" },
  { word: "きれい [Kirei]", meaning: "예쁘다, 깨끗하다", example: "きれいな花ですね。" },
  { word: "元気 [Genki]", meaning: "건강함", example: "お元気ですか？" },
  { word: "有名 [Yūmei]", meaning: "유명함", example: "彼は有名な歌手です。" },
  { word: "静か [Shizuka]", meaning: "조용함", example: "図書館は静かです。" },
  { word: "暇 [Hima]", meaning: "한가함", example: "今日は暇です。" },
  { word: "上 [Ue]", meaning: "위", example: "机の上にあります。" },
  { word: "下 [Shita]", meaning: "아래", example: "椅子の下にあります。" },
  { word: "前 [Mae]", meaning: "앞", example: "駅の前にいます。" },
  { word: "後ろ [Ushiro]", meaning: "뒤", example: "後ろに誰かいます。" },
  { word: "右 [Migi]", meaning: "오른쪽", example: "右に曲がってください。" },
  { word: "左 [Hidari]", meaning: "왼쪽", example: "左を見てください。" },
  { word: "中 [Naka]", meaning: "안", example: "鞄の中にあります。" },
  { word: "外 [Soto]", meaning: "밖", example: "外へ出ます。" },
  { word: "近く [Chikaku]", meaning: "가까움", example: "駅の近くです。" },
  { word: "遠い [Tooi]", meaning: "멀다", example: "家から遠いです。" },
  { word: "一 [Ichi]", meaning: "1", example: "一時間待ちます。" },
  { word: "二 [Ni]", meaning: "2", example: "二人で行きます。" },
  { word: "三 [San]", meaning: "3", example: "三つ買います。" },
  { word: "人 [Hito]", meaning: "사람", example: "たくさんの人がいます。" }
];

export const HINDI_100_WORDS = [
  { word: "नमस्ते [Namaste]", meaning: "안녕하세요", example: "नमस्ते, आप कैसे हैं?" },
  { word: "धन्यवाद [Dhanyavaad]", meaning: "감사합니다", example: "आपकी मदद के लिए धन्यवाद।" },
  { word: "अलविदा [Alvida]", meaning: "안녕히 가세요", example: "अलविदा, फिर मिलेंगे।" },
  { word: "कृपया [Kripaya]", meaning: "부탁합니다", example: "कृपया यहाँ बैठिए।" },
  { word: "दोस्त [Dost]", meaning: "친구", example: "वह मेरा सबसे अच्छा दोस्त है।" },
  { word: "घर [Ghar]", meaning: "집", example: "यह मेरा घर है।" },
  { word: "समय [Samay]", meaning: "시간", example: "समय बहुत कीमती है।" },
  { word: "काम [Kaam]", meaning: "일", example: "आज बहुत काम है।" },
  { word: "खाना [Khaana]", meaning: "먹다/음식", example: "मुझे भारतीय खाना पसंद है।" },
  { word: "पीना [Peena]", meaning: "마시다", example: "पानी पीना ज़रूरी है।" },
  { word: "पानी [Paani]", meaning: "물", example: "मुझे पानी चाहिए।" },
  { word: "दूध [Doodh]", meaning: "우유", example: "बच्चा दूध पी रहा है।" },
  { word: "रोटी [Roti]", meaning: "빵 (로티)", example: "मैं रोटी खा रहा हूँ।" },
  { word: "सब्जी [Sabzi]", meaning: "채소", example: "सब्जी ताज़ी है।" },
  { word: "फल [Phal]", meaning: "과일", example: "फल सेहत के लिए अच्छे हैं।" },
  { word: "सेब [Seb]", meaning: "사과", example: "यह एक मीठा सेब है।" },
  { word: "केला [Kela]", meaning: "바나나", example: "मुझे केला पसंद है।" },
  { word: "आम [Aam]", meaning: "망고", example: "आम फलों का राजा है।" },
  { word: "चाय [Chai]", meaning: "차 (마시는 차)", example: "क्या आप चाय पिएंगे?" },
  { word: "कॉफी [Coffee]", meaning: "커피", example: "मुझे गरम कॉफी पसंद है।" },
  { word: "शक्कर [Shakkar]", meaning: "설탕", example: "चाय में शक्कर कम है।" },
  { word: "नमक [Namak]", meaning: "소금", example: "खाने में नमक डालो।" },
  { word: "मिर्च [Mirch]", meaning: "고추", example: "यह मिर्च बहुत तीखी है।" },
  { word: "बड़ा [Bada]", meaning: "큰", example: "यह एक बड़ा घर है।" },
  { word: "छोटा [Chhota]", meaning: "작은", example: "वह छोटा बच्चा है।" },
  { word: "अच्छा [Achha]", meaning: "좋은", example: "यह बहुत अच्छा विचार है।" },
  { word: "बुरा [Bura]", meaning: "나쁜", example: "झूठ बोलना बुरी बात है।" },
  { word: "नया [Naya]", meaning: "새로운", example: "मेरे पास एक नया फोन है।" },
  { word: "पुराना [Purana]", meaning: "오래된", example: "यह किताब पुरानी है।" },
  { word: "सुंदर [Sundar]", meaning: "아름다운", example: "वह बहुत सुंदर है।" },
  { word: "साफ़ [Saaf]", meaning: "깨끗한", example: "कमरा साफ़ करो।" },
  { word: "गंदा [Ganda]", meaning: "더러운", example: "हाथ गंदे हैं।" },
  { word: "खुश [Khush]", meaning: "행복한", example: "मैं बहुत खुश हूँ।" },
  { word: "दुखी [Dukhi]", meaning: "슬픈", example: "वह आज दुखी है।" },
  { word: "गर्म [Garm]", meaning: "뜨거운", example: "दूध गर्म है।" },
  { word: "ठंडा [Thanda]", meaning: "차가운", example: "पानी ठंडा है।" },
  { word: "सस्ता [Sasta]", meaning: "저렴한", example: "यह कपड़ा सस्ता है।" },
  { word: "महंगा [Mahanga]", meaning: "비싼", example: "सोना महंगा है।" },
  { word: "भारी [Bhaari]", meaning: "무거운", example: "यह बक्सा बहुत भारी है।" },
  { word: "हल्का [Halka]", meaning: "가벼운", example: "यह पंख हल्का है।" },
  { word: "तेज़ [Tez]", meaning: "빠른", example: "घोड़ा तेज़ दौड़ता है।" },
  { word: "धीरे [Dheere]", meaning: "천천히", example: "धीरे चलो।" },
  { word: "ऊपर [Oopar]", meaning: "위", example: "पंखा ऊपर है।" },
  { word: "नीचे [Neeche]", meaning: "아래", example: "बिल्ली मेज के नीचे है।" },
  { word: "अंदर [Andar]", meaning: "안", example: "अंदर आ जाइए।" },
  { word: "बाहर [Baahar]", meaning: "밖", example: "बाहर मत जाओ।" },
  { word: "पास [Paas]", meaning: "가까이", example: "मेरे पास आओ।" },
  { word: "दूर [Door]", meaning: "멀리", example: "स्कूल बहुत दूर है।" },
  { word: "यहाँ [Yahan]", meaning: "여기", example: "यहाँ बैठो।" },
  { word: "वहाँ [Wahan]", meaning: "저기", example: "वहाँ देखो।" },
  { word: "आज [Aaj]", meaning: "오늘", example: "आज रविवार है।" },
  { word: "कल [Kal]", meaning: "내일/어제", example: "कल छुट्टी है।" },
  { word: "अब [Ab]", meaning: "지금", example: "अब घर चलो।" },
  { word: "रात [Raat]", meaning: "밤", example: "रात हो गई है।" },
  { word: "दिन [Din]", meaning: "낮/일", example: "दिन साफ़ है।" },
  { word: "सुबह [Subah]", meaning: "아침", example: "सुबह जल्दी उठो।" },
  { word: "शाम [Shaam]", meaning: "저녁", example: "शाम को मिलते हैं।" },
  { word: "पिता [Pita]", meaning: "아버지", example: "मेरे पिता घर पर हैं।" },
  { word: "माता [Maata]", meaning: "어머니", example: "माता जी खाना बना रही हैं।" },
  { word: "भाई [Bhai]", meaning: "형제/남동생/오빠", example: "वह मेरा भाई है।" },
  { word: "बहन [Behen]", meaning: "자매/여동생/언니", example: "मेरी एक छोटी बहन है।" },
  { word: "बेटा [Beta]", meaning: "아들", example: "मेरा बेटा स्कूल गया है।" },
  { word: "बेटी [Beti]", meaning: "딸", example: "मेरी बेटी बहुत समझदार है।" },
  { word: "पति [Pati]", meaning: "남편", example: "वह उसके पति हैं।" },
  { word: "पत्नी [Patni]", meaning: "아내", example: "उसकी पत्नी डॉक्टर है।" },
  { word: "आदमी [Aadmi]", meaning: "남자/사람", example: "वह एक अच्छा आदमी है।" },
  { word: "औरत [Aurat]", meaning: "여자", example: "वह औरत काम कर रही है।" },
  { word: "बच्चा [Bachha]", meaning: "아이", example: "बच्चा खेल रहा है।" },
  { word: "लड़का [Ladka]", meaning: "소년", example: "लड़का दौड़ रहा है।" },
  { word: "लड़की [Ladki]", meaning: "소녀", example: "लड़की पढ़ रही है।" },
  { word: "पशु [Pashu]", meaning: "동물", example: "जंगल में बहुत पशु हैं।" },
  { word: "गाय [Gaay]", meaning: "암소", example: "गाय दूध देती है।" },
  { word: "कुत्ता [Kutta]", meaning: "개", example: "कुत्ता वफादार होता है।" },
  { word: "बिल्ली [Billi]", meaning: "고양이", example: "बिल्ली दूध पीती है।" },
  { word: "हाथी [Haathi]", meaning: "코끼리", example: "हाथी बहुत बड़ा होता है।" },
  { word: "शेर [Sher]", meaning: "사자", example: "शेर जंगल का राजा है।" },
  { word: "पक्षी [Pakshi]", meaning: "새", example: "आकाश में पक्षी उड़ रहे हैं।" },
  { word: "मछली [Machhli]", meaning: "물고기", example: "मछली पानी में रहती है।" },
  { word: "आकाश [Aakash]", meaning: "하늘", example: "आकाश नीला है।" },
  { word: "सूर्य [Surya]", meaning: "태양", example: "सूर्य पूर्व से निकलता है।" },
  { word: "चंद्रमा [Chandrama]", meaning: "달", example: "चंद्रमा रात को चमकता है।" },
  { word: "सितारा [Sitara]", meaning: "별", example: "आसमान में बहुत सितारे हैं।" },
  { word: "बादल [Baadal]", meaning: "구름", example: "आसमान में बादल छाए हैं।" },
  { word: "बारिश [Baarish]", meaning: "비", example: "आज बारिश होगी।" },
  { word: "हवा [Hawa]", meaning: "바람/공기", example: "ठंडी हवा चल रही है।" },
  { word: "पहाड़ [Pahaad]", meaning: "산", example: "हिमालय एक ऊँचा पहाड़ है।" },
  { word: "नदी [Nadi]", meaning: "강", example: "गंगा एक पवित्र नदी है।" },
  { word: "समुद्र [Samudra]", meaning: "바다", example: "समुद्र बहुत गहरा है।" },
  { word: "शहर [Shehar]", meaning: "도시", example: "मैं दिल्ली शहर में रहता हूँ।" },
  { word: "गाँव [Gaon]", meaning: "마을/시골", example: "मेरा गाँव बहुत सुंदर है।" },
  { word: "सड़क [Sadak]", meaning: "도로", example: "सड़क साफ़ है।" },
  { word: "गाड़ी [Gaadi]", meaning: "차/기차", example: "गाड़ी समय पर आई।" },
  { word: "दुकान [Dukaan]", meaning: "상점", example: "दुकान बंद है।" },
  { word: "बाज़ार [Baazaar]", meaning: "시장", example: "बाज़ार में बहुत भीड़ है।" },
  { word: "किताब [Kitaab]", meaning: "책", example: "मैं किताब पढ़ रहा हूँ।" },
  { word: "कलम [Kalam]", meaning: "펜", example: "यह मेरी कलम है।" },
  { word: "कागज़ [Kaagaz]", meaning: "종이", example: "कागज़ पर लिखो।" },
  { word: "स्कूल [School]", meaning: "학교", example: "बच्चे स्कूल जा रहे हैं।" },
  { word: "अध्यापक [Adhyapak]", meaning: "선생님", example: "अध्यापक पढ़ा रहे हैं।" },
  { word: "छात्र [Chhatra]", meaning: "학생", example: "छात्र मेहनत कर रहे हैं।" }
];

export const ARABIC_100_WORDS = [
  { word: "مرحباً [Marhaban]", meaning: "안녕하세요", example: "مرحباً بك في بيتي." },
  { word: "شكراً [Shukran]", meaning: "감사합니다", example: "شكراً جزيلاً لك." },
  { word: "وداعاً [Wada'an]", meaning: "안녕히 가세요", example: "وداعاً، أراك قريباً." },
  { word: "من فضلك [Min fadlak]", meaning: "부탁합니다", example: "أعطني القلم من فضلك." },
  { word: "صديق [Sadiq]", meaning: "친구", example: "هو صديق قديم لي." },
  { word: "بيت [Bayt]", meaning: "집", example: "بيتي بعيد عن هنا." },
  { word: "وقت [Waqt]", meaning: "시간", example: "ليس لدي وقت للعب." },
  { word: "عمل [Amal]", meaning: "일", example: "أحب عملي كثيراً." },
  { word: "أكل [Akl]", meaning: "먹다", example: "أريد أكل التفاح." },
  { word: "شرب [Shurb]", meaning: "마시다", example: "يجب شرب الكثير من الماء." },
  { word: "ماء [Ma']", meaning: "물", example: "أحتاج إلى شرب الماء." },
  { word: "خبز [Khubz]", meaning: "빵", example: "أريد شراء الخبز الطازج." },
  { word: "حليب [Halib]", meaning: "우유", example: "الحليب مفيد للصحة." },
  { word: "لحم [Lahm]", meaning: "고기", example: "أنا لا آكل اللحم." },
  { word: "دجاج [Dajaj]", meaning: "닭고기", example: "الدجاج المشوي لذيذ." },
  { word: "سمك [Samak]", meaning: "물고기", example: "السمك يعيش في الماء." },
  { word: "أرز [Arz]", meaning: "쌀/밥", example: "أحب أكل الأرز مع الدجاج." },
  { word: "فاكهة [Fakihah]", meaning: "과일", example: "أتناول الفاكهة كل يوم." },
  { word: "خضروات [Khudarawat]", meaning: "채소", example: "الخضروات طازجة." },
  { word: "قهوة [Qahwah]", meaning: "커피", example: "أشرب القهوة في الصباح." },
  { word: "شاي [Shay]", meaning: "차 (마시는 차)", example: "هل تحب الشاي الأخضر؟" },
  { word: "سكر [Sukkar]", meaning: "설탕", example: "لا أضع السكر في الشاي." },
  { word: "ملح [Milh]", meaning: "소금", example: "الملح ضروري للطبخ." },
  { word: "فطور [Futur]", meaning: "아침 식사", example: "ماذا أكلت في الفطور؟" },
  { word: "غداء [Ghada']", meaning: "점심 식사", example: "وقت الغداء قد حان." },
  { word: "عشاء [Asha']", meaning: "저녁 식사", example: "العشاء جاهز الآن." },
  { word: "كبير [Kabir]", meaning: "큰", example: "هذا البيت كبير جداً." },
  { word: "صغير [Saghir]", meaning: "작은", example: "عندي قط صغير." },
  { word: "جميل [Jamil]", meaning: "아름다운/멋진", example: "هذا المنظر جميل." },
  { word: "قبيح [Qabih]", meaning: "못생긴/추한", example: "هذا تصرف قبيح." },
  { word: "جديد [Jadid]", meaning: "새로운", example: "اشتريت سيارة جديدة." },
  { word: "قديم [Qadim]", meaning: "오래된", example: "هذا الكتاب قديم جداً." },
  { word: "جيد [Jayyid]", meaning: "좋은", example: "هذا عمل جيد." },
  { word: "سيء [Sayyi']", meaning: "나쁜", example: "الطقس سيء اليوم." },
  { word: "حار [Harr]", meaning: "뜨거운/더운", example: "الجو حار في الصيف." },
  { word: "بارد [Barid]", meaning: "차가운/추운", example: "أحب العصير البارد." },
  { word: "سريع [Sari']", meaning: "빠른", example: "القطار سريع جداً." },
  { word: "بطيء [Bati']", meaning: "느린", example: "هذا الرجل بطيء في المشي." },
  { word: "قريب [Qarib]", meaning: "가까운", example: "بيتي قريب من المسجد." },
  { word: "بعيد [Ba'id]", meaning: "멀리", example: "المطار بعيد عن المدينة." },
  { word: "طويل [Tawil]", meaning: "긴/키가 큰", example: "هو رجل طويل." },
  { word: "قصير [Qasir]", meaning: "짧은/키가 작은", example: "هذا قلم قصير." },
  { word: "غني [Ghaniyy]", meaning: "부유한", example: "هو رجل غني جداً." },
  { word: "فقير [Faqir]", meaning: "가난한", example: "ساعد الرجل الفقير." },
  { word: "سهل [Sahl]", meaning: "쉬운", example: "الامتحان كان سهلاً." },
  { word: "صعب [Sa'b]", meaning: "어려운", example: "هذا السؤال صعب." },
  { word: "نعم [Na'am]", meaning: "네", example: "نعم، أنا موافق." },
  { word: "لا [La]", meaning: "아니요", example: "لا، شكراً لك." },
  { word: "أنا [Ana]", meaning: "나", example: "أنا طالب في الجامعة." },
  { word: "أنت [Anta]", meaning: "너 (남성)", example: "أنت صديق مخلص." },
  { word: "هو [Huwa]", meaning: "그", example: "هو معلم متميز." },
  { word: "هي [Hiya]", meaning: "그녀", example: "هي طبيبة ناجحة." },
  { word: "هنا [Huna]", meaning: "여기", example: "اجلس هنا من فضلك." },
  { word: "هناك [Hunaka]", meaning: "저기", example: "هناك مدرسة كبيرة." },
  { word: "اليوم [Al-yawm]", meaning: "오늘", example: "اليوم هو يوم جميل." },
  { word: "غداً [Ghadan]", meaning: "내일", example: "سأراك غداً." },
  { word: "أمس [Ams]", meaning: "어제", example: "ذهبت إلى السوق أمس." },
  { word: "الآن [Al-an]", meaning: "지금", example: "يجب أن أذهب الآن." },
  { word: "صباح [Sabah]", meaning: "아침", example: "صباح الخير." },
  { word: "مساء [Masa']", meaning: "저녁", example: "مساء النور." },
  { word: "ليل [Layl]", meaning: "밤", example: "الليل هادئ جداً." },
  { word: "يوم [Yawm]", meaning: "일/낮", example: "أعمل كل يوم." },
  { word: "أسبوع [Usbu']", meaning: "주", example: "هناك سبعة أيام في الأسبوع." },
  { word: "شهر [Shahr]", meaning: "월", example: "أنا هنا منذ شهر." },
  { word: "سنة [Sanah]", meaning: "년", example: "سنة جديدة سعيدة." },
  { word: "مدينة [Madinah]", meaning: "도시", example: "أسكن في مدينة دبي." },
  { word: "قرية [Qaryah]", meaning: "마을", example: "قريتي صغيرة وجميلة." },
  { word: "طريق [Tariq]", meaning: "길/도로", example: "هذا الطريق طويل." },
  { word: "سيارة [Sayyarah]", meaning: "자동차", example: "عندي سيارة حمراء." },
  { word: "حافلة [Hafilah]", meaning: "버스", example: "أركب الحافلة كل يوم." },
  { word: "طائرة [Ta'irah]", meaning: "비행기", example: "سأذهب بالطائرة." },
  { word: "سوق [Suq]", meaning: "시장", example: "السوق مزدحم بالناس." },
  { word: "محل [Mahall]", meaning: "상점", example: "هذا المحل يبيع الملابس." },
  { word: "مطعم [Mat'am]", meaning: "식당", example: "هذا مطعم عربي." },
  { word: "مدرسة [Madrasah]", meaning: "학교", example: "أذهب إلى المدرسة." },
  { word: "جامعة [Jami'ah]", meaning: "대학교", example: "أدرس في الجامعة." },
  { word: "كتاب [Kitab]", meaning: "책", example: "أقرأ كتاباً مفيداً." },
  { word: "قلم [Qalam]", meaning: "펜", example: "أكتب بالقلم الأزرق." },
  { word: "ورقة [Waraqah]", meaning: "종이", example: "أحتاج إلى ورقة." },
  { word: "رجل [Rajul]", meaning: "남자", example: "هذا رجل حكيم." },
  { word: "امرأة [Imra'ah]", meaning: "여자", example: "هي امرأة قوية." },
  { word: "ولد [Walad]", meaning: "소년/아이", example: "الولد يلعب بالكرة." },
  { word: "بنت [Bint]", meaning: "소녀/딸", example: "البنت تدرس بجد." },
  { word: "أب [Ab]", meaning: "아버지", example: "أبي يعمل مهندساً." },
  { word: "أم [Umm]", meaning: "어머니", example: "أمي تحب الطبخ." },
  { word: "أخ [Akh]", meaning: "형제/남동생", example: "أخي أكبر مني." },
  { word: "أخت [Ukht]", meaning: "자매/여동생", example: "أختي طالبة ذكية." },
  { word: "حيوان [Hayawan]", meaning: "동물", example: "الأسد حيوان مفترس." },
  { word: "كلب [Kalb]", meaning: "개", example: "عندي كلب أليف." },
  { word: "قطة [Qittah]", meaning: "고양이", example: "القطة تحب الحليب." },
  { word: "جمل [Jamal]", meaning: "낙타", example: "الجمل سفينة الصحراء." },
  { word: "حصان [Hisan]", meaning: "말", example: "الحصان يركض بسرعة." },
  { word: "عصفور [Usfur]", meaning: "새", example: "العصفور يغرد فوق الشجرة." },
  { word: "شجرة [Shajarah]", meaning: "나무", example: "هذه شجرة زيتون." },
  { word: "زهرة [Zahrah]", meaning: "꽃", example: "الزهرة حمراء وجميلة." },
  { word: "بحر [Bahr]", meaning: "바다", example: "البحر واسع وعميق." },
  { word: "نهر [Nahr]", meaning: "강", example: "أشرب من مياه النهر." },
  { word: "جبل [Jabal]", meaning: "산", example: "هذا جبل مرتفع جداً." },
  { word: "شمس [Shams]", meaning: "태양", example: "الشمس تشرق كل صباح." },
  { word: "قمر [Qamar]", meaning: "달", example: "القمر يضيء في الليل." },
  { word: "نجمة [Najmah]", meaning: "별", example: "أرى نجمة في السماء." }
];

export const CHINESE_100_WORDS = [
  { word: "你好 [Nǐ hǎo]", meaning: "안녕하세요", example: "你好！很高兴见到你。" },
  { word: "谢谢 [Xièxiè]", meaning: "감사합니다", example: "谢谢你的礼物。" },
  { word: "再见 [Zàijiàn]", meaning: "안녕히 가세요", example: "明天见，再见。" },
  { word: "对不起 [Duìbùqǐ]", meaning: "죄송합니다", example: "对不起，我迟到了。" },
  { word: "没关系 [Méiguānxì]", meaning: "괜찮습니다", example: "没关系，别客气。" },
  { word: "我 [Wǒ]", meaning: "나, 저", example: "我是一个学生。" },
  { word: "你 [Nǐ]", meaning: "너, 당신", example: "你吃饭了吗？" },
  { word: "是 [Shì]", meaning: "~이다", example: "他是我的爸爸。" },
  { word: "不 [Bù]", meaning: "아니다, ~않다", example: "我不喜欢下雨。" },
  { word: "有 [Yǒu]", meaning: "있다, 가지고 있다", example: "我有一本书。" },
  { word: "什么 [Shénme]", meaning: "무엇", example: "你在看什么？" },
  { word: "漂亮 [Piàoliang]", meaning: "예쁘다", example: "你穿这件衣服很漂亮。" },
  { word: "老师 [Lǎoshī]", meaning: "선생님", example: "王老师教我们中文。" },
  { word: "学生 [Xuésheng]", meaning: "학생", example: "那里有很多学生。" },
  { word: "朋友 [Péngyou]", meaning: "친구", example: "他是我最好的朋友。" },
  { word: "大 [Dà]", meaning: "크다", example: "这个房子很大。" },
  { word: "小 [Xiǎo]", meaning: "작다", example: "这只猫很小。" },
  { word: "好 [Hǎo]", meaning: "좋다", example: "今天天气很好。" },
  { word: "多 [Duō]", meaning: "많다", example: "这里人很多。" },
  { word: "少 [Shǎo]", meaning: "적다", example: "钱很少。" },
  { word: "喝 [Hē]", meaning: "마시다", example: "我要喝咖啡。" },
  { word: "吃 [Chī]", meaning: "먹다", example: "你吃中餐吗？" },
  { word: "去 [Qù]", meaning: "가다", example: "我去商店。" },
  { word: "来 [Lái]", meaning: "오다", example: "他来了。" },
  { word: "看 [Kàn]", meaning: "보다", example: "我看电影。" }
];

export const FRENCH_100_WORDS = [
  { word: "bonjour", meaning: "안녕하세요", example: "Bonjour tout le monde." },
  { word: "merci", meaning: "감사합니다", example: "Merci beaucoup." },
  { word: "au revoir", meaning: "안녕히 가세요", example: "Au revoir, à demain." },
  { word: "s'il vous plaît", meaning: "부탁합니다", example: "Un café, s'il vous plaît." },
  { word: "ami", meaning: "친구", example: "C'est mon meilleur ami." },
  { word: "maison", meaning: "집", example: "Ma maison est bleue." },
  { word: "temps", meaning: "시간, 날씨", example: "Quel temps fait-il?" },
  { word: "travail", meaning: "일, 직장", example: "J'aime mon travail." },
  { word: "manger", meaning: "먹다", example: "Je veux manger." },
  { word: "boire", meaning: "마시다", example: "Je bois de l'eau." },
  { word: "vouloir", meaning: "원하다", example: "Je veux un croissant." },
  { word: "pouvoir", meaning: "할 수 있다", example: "Je peux t'aider." },
  { word: "savoir", meaning: "알다", example: "Je ne sais pas." },
  { word: "petit", meaning: "작은", example: "C'est un petit chat." },
  { word: "grand", meaning: "큰", example: "Il est très grand." }
];

export const RUSSIAN_100_WORDS = [
  { word: "привет [Privet]", meaning: "안녕", example: "Привет! Как дела?" },
  { word: "спасибо [Spasibo]", meaning: "감사합니다", example: "Большое спасибо." },
  { word: "пока [Poka]", meaning: "안녕 (헤어질 때)", example: "Пока, до завтра." },
  { word: "пожалуйста [Pozhaluysta]", meaning: "부탁합니다/천만에요", example: "Пожалуйста, помогите мне." },
  { word: "друг [Drug]", meaning: "친구", example: "Он мой лучший друг." },
  { word: "дом [Dom]", meaning: "집", example: "Это мой дом." },
  { word: "время [Vremya]", meaning: "시간", example: "У меня нет времени." },
  { word: "работа [Rabota]", meaning: "일, 직장", example: "Где твоя работа?" },
  { word: "есть [Est']", meaning: "먹다", example: "Я хочу есть." },
  { word: "пить [Pit']", meaning: "마시다", example: "Дай мне пить." }
];

export const BENGALI_100_WORDS = [
  { word: "হ্যালো [Hyālō]", meaning: "안녕", example: "হ্যালো, কেমন আছো?" },
  { word: "ধন্যবাদ [Dhanyabāda]", meaning: "감사합니다", example: "সাহায্যের জন্য धन्यवाद।" },
  { word: "বিদায় [Bidāẏa]", meaning: "안녕히 가세요", example: "বিদায়, আবার দেখা হবে।" },
  { word: "দয়া করে [Dayā karē]", meaning: "부탁합니다", example: "দয়া করে জল দিন।" },
  { word: "বন্ধু [Bandhu]", meaning: "친구", example: "সে আমার ভালো বন্ধু।" },
  { word: "বাড়ি [Bāṛi]", meaning: "집", example: "এটা আমার বাড়ি।" }
];

export const PORTUGUESE_100_WORDS = [
  { word: "olá", meaning: "안녕", example: "Olá! Tudo bem?" },
  { word: "obrigado", meaning: "감사합니다", example: "Obrigado pela ajuda." },
  { word: "adeus", meaning: "안녕히 가세요", example: "Adeus, até amanhã." },
  { word: "por favor", meaning: "부탁합니다", example: "Café, por favor." },
  { word: "amigo", meaning: "친구", example: "Ele é meu melhor amigo." },
  { word: "casa", meaning: "집", example: "Minha casa é amarela." }
];

export const SAMPLE_DATA_MAP: Record<string, any[]> = {
  en: ESSENTIAL_100_WORDS,
  zh: CHINESE_100_WORDS,
  hi: HINDI_100_WORDS,
  es: SPANISH_100_WORDS,
  fr: FRENCH_100_WORDS,
  ar: ARABIC_100_WORDS,
  bn: BENGALI_100_WORDS,
  pt: PORTUGUESE_100_WORDS,
  ru: RUSSIAN_100_WORDS,
  ja: JAPANESE_100_WORDS
};
